name: CI

on:
  push:
    branches: [main]
    paths:
      - package.json
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - package.json
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@master
      - name: Run tests
        uses: tree-sitter/parser-test-action@master
        with:
          test-rust: true
          # https://github.com/tree-sitter/node-tree-sitter/issues/268
          test-node: false
          test-python: true
          test-go: true
          test-swift: true
