name: Lint

on:
  push:
    branches: [main]
    paths:
      - grammar.js
  pull_request:
    paths:
      - grammar.js

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: pnpm/setup@v2
      - name: Install modules
        run: pnpm ci
      - name: Run ESLint
        run: pnpm run lint
