name: Queries-CI

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths:
      - queries/**
  pull_request:
    paths:
      - queries/**

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install luarocks -y
          sudo luarocks install luacheck

      - name: Run Luacheck
        run: luacheck .

  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
